# Generated by Django 4.0.6 on 2022-08-01 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'raid in progress'), ('success', 'raid success'), ('fail', 'raid fail')], default='in_progress', max_length=200)),
                ('enter_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('time_limit', models.PositiveIntegerField(default=180)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raid_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'raid_histories',
            },
        ),
    ]
